// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhikklreafmkmepckwgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oaWtrbHJlYWZta21lcGNrd2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjA0MDYsImV4cCI6MjA2NjU5NjQwNn0.PAZDdnICPswJOQgH3O6oB84_fxJDk64ADivPIg61Nnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});